routes/web.php
    Route::get('administrative_areas/dt','Admin\AdministrativeAreaController@toDatatable')->name('administrative_areas.dt');
	Route::resource('administrative_areas', 'Admin\AdministrativeAreaController');
	
	Route::get('operative_areas/dt','Admin\OperativeAreaController@toDatatable')->name('operative_areas.dt');
	Route::resource('operative_areas', 'Admin\OperativeAreaController');
	
	Route::get('payment_methods/dt','Admin\PaymentMethodController@toDatatable')->name('payment_methods.dt');
	Route::resource('payment_methods', 'Admin\PaymentMethodController');

	Route::get('experience_ranges/dt','Admin\ExperienceRangeController@toDatatable')->name('experience_ranges.dt');
	Route::resource('experience_ranges', 'Admin\ExperienceRangeController');
	
	Route::get('suppliers/dt','Admin\SupplierController@toDatatable')->name('suppliers.dt');
	Route::get('suppliers/invitation','Admin\SupplierController@formInvitation')->name('suppliers.form_invitation');
	Route::post('suppliers/invitation','Admin\SupplierController@sendInvitation')->name('suppliers.send_invitation');
	Route::get('suppliers/{supplier}/products','Admin\SupplierController@formProducts')->name('supplier.edit_products');
	Route::post('suppliers/{supplier}/products','Admin\SupplierController@updateProducts')->name('supplier.update_products');
	Route::resource('suppliers', 'Admin\SupplierController');

	/*RUTAS PARA LA ORDENES DE PROVEEDORES*/
	Route::get('supplier_orders/{supplier_order}/ordenes_json','Admin\SupplierOrderController@orderJson')->name('supplier_orders.orders_json');
	Route::get('supplier_orders/{supplier_order}/ordenes','Admin\SupplierOrderController@listOrder')->name('supplier_orders.orders_index');

	Route::get('supplier_orders/create_order/{supplier_order}','Admin\SupplierOrderController@formCreateOrder')->name('supplier_orders.form_order');
	Route::put('supplier_orders/create_order/{supplier_order}','Admin\SupplierOrderController@storeOrder')->name('supplier_orders.store_order');
	
	Route::get('supplier_orders/selection_matrix/{supplier_order}','Admin\SupplierOrderController@selectionMatrix')->name('supplier_orders.selection_matrix');
	Route::get('supplier_orders/observaciones/{supplier_order}','Admin\SupplierOrderController@observaciones')->name('supplier_orders.observaciones');
	Route::get('supplier_orders/cotizaciones/{supplier_order}','Admin\SupplierOrderController@cotizaciones')->name('supplier_orders.cotizaciones');

	Route::get('supplier_orders/requisition/dt','Admin\SupplierOrderController@toDatatableRequisition')->name('supplier_orders.dt_requisition');
	Route::get('supplier_orders/requisition','Admin\SupplierOrderController@indexRequisition')->name('supplier_orders.index_requisition');
	Route::get('supplier_orders/requisition/create','Admin\SupplierOrderController@createRequisition')->name('supplier_orders.create_requisition');
	Route::post('supplier_orders/requisition','Admin\SupplierOrderController@storeRequisition')->name('supplier_orders.store_requisition');

	Route::get('supplier_orders/requisition/pdf/{supplier_order}','Admin\SupplierOrderController@pdfRequisition')->name('supplier_orders.pdf_requisition');

	Route::get('supplier_orders/autorization/dt','Admin\SupplierOrderController@toDatatableAutorization')->name('supplier_orders.dt_autorization');
	Route::get('supplier_orders/autorization','Admin\SupplierOrderController@indexAutorization')->name('supplier_orders.index_autorization');
	Route::get('supplier_orders/autorization/{supplier_order}/edit','Admin\SupplierOrderController@editAutorization')->name('supplier_orders.edit_autorization');
	Route::put('supplier_orders/autorization/{supplier_order}','Admin\SupplierOrderController@updateAutorization')->name('supplier_orders.update_autorization');
	Route::get('supplier_orders/autorization/{supplier_order}/reject','Admin\SupplierOrderController@rejectAutorization')->name('supplier_orders.reject_autorization');
	Route::put('supplier_orders/autorization/{supplier_order}/refuse','Admin\SupplierOrderController@refuseAutorization')->name('supplier_orders.refuse_autorization');
	Route::get('supplier_orders/autorization/{supplier_order}/pause','Admin\SupplierOrderController@pauseAutorization')->name('supplier_orders.pause_autorization');
	Route::put('supplier_orders/autorization/{supplier_order}/stop','Admin\SupplierOrderController@stopAutorization')->name('supplier_orders.stop_autorization');

	Route::get('supplier_orders/quotation/dt','Admin\SupplierOrderController@toDatatableQuotation')->name('supplier_orders.dt_quotation');
	Route::get('supplier_orders/quotation','Admin\SupplierOrderController@indexQuotation')->name('supplier_orders.index_quotation');
	Route::get('supplier_orders/quotation/{supplier_order}/edit','Admin\SupplierOrderController@editQuotation')->name('supplier_orders.edit_quotation');
	Route::put('supplier_orders/quotation/{supplier_order}','Admin\SupplierOrderController@updateQuotation')->name('supplier_orders.update_quotation');

	Route::get('supplier_orders/regenerate/{supplier_order}','Admin\SupplierOrderController@regenerateGet')->name('supplier_orders.regenerate_get');
	Route::put('supplier_orders/regenerate/{supplier_order}','Admin\SupplierOrderController@regeneratePut')->name('supplier_orders.regenerate_put');

	Route::get('supplier_orders/supplier_quote/dt','Admin\SupplierOrderController@toDatatableSupplierQuote')->name('supplier_orders.dt_supplier_quote');
	Route::get('supplier_orders/supplier_quote','Admin\SupplierOrderController@indexSupplierQuote')->name('supplier_orders.index_supplier_quote');
	Route::get('supplier_orders/supplier_quote/{quotation}/edit','Admin\SupplierOrderController@editSupplierQuote')->name('supplier_orders.edit_supplier_quote');
	Route::put('supplier_orders/supplier_quote/{quotation}','Admin\SupplierOrderController@updateSupplierQuote')->name('supplier_orders.update_supplier_quote');

	Route::get('supplier_orders/preselection/dt','Admin\SupplierOrderController@toDatatablePreselection')->name('supplier_orders.dt_preselection');
	Route::get('supplier_orders/preselection','Admin\SupplierOrderController@indexPreselection')->name('supplier_orders.index_preselection');
	Route::get('supplier_orders/preselection/{supplier_order}/edit','Admin\SupplierOrderController@editPreselection')->name('supplier_orders.edit_preselection');
	Route::put('supplier_orders/preselection/{supplier_order}','Admin\SupplierOrderController@updatePreselection')->name('supplier_orders.update_preselection');

	Route::get('supplier_orders/preselection/pdf/{purchase_order}','Admin\SupplierOrderController@pdfPurchaseOrder')->name('supplier_orders.pdf_purchase_order');

	Route::get('supplier_orders/send/dt','Admin\SupplierOrderController@toDatatableSend')->name('supplier_orders.dt_send');
	Route::get('supplier_orders/send','Admin\SupplierOrderController@indexSend')->name('supplier_orders.index_send');
	//Route::get('supplier_orders/send/{supplier_order}/edit','Admin\SupplierOrderController@editSend')->name('supplier_orders.edit_send');
	Route::put('supplier_orders/send/{supplier_order}','Admin\SupplierOrderController@updateSend')->name('supplier_orders.update_send');

	Route::get('supplier_orders/score/dt','Admin\SupplierOrderController@toDatatableScore')->name('supplier_orders.dt_score');
	Route::get('supplier_orders/score','Admin\SupplierOrderController@indexScore')->name('supplier_orders.index_score');
	Route::get('supplier_orders/score/{supplier_order}/edit','Admin\SupplierOrderController@editScore')->name('supplier_orders.edit_score');
	Route::put('supplier_orders/score/{supplier_order}','Admin\SupplierOrderController@updateScore')->name('supplier_orders.update_score');


	Route::get('supplier_orders/dt','Admin\SupplierOrderController@toDatatable')->name('supplier_orders.dt');
	Route::resource('supplier_orders', 'Admin\SupplierOrderController');

	/***************************************/

	Route::get('order_priorities/dt','Admin\OrderPriorityController@toDatatable')->name('order_priorities.dt');
	Route::resource('order_priorities', 'Admin\OrderPriorityController');

	Route::get('measurement_units/dt','Admin\MeasurementUnitController@toDatatable')->name('measurement_units.dt');
	Route::resource('measurement_units', 'Admin\MeasurementUnitController');

	Route::get('quotations/dt','Admin\QuotationController@toDatatable')->name('quotations.dt');
	Route::resource('quotations', 'Admin\QuotationController');

	Route::get('satisfaction_questions/dt','Admin\SatisfactionQuestionController@toDatatable')->name('satisfaction_questions.dt');
	Route::resource('satisfaction_questions', 'Admin\SatisfactionQuestionController');
	
	Route::get('purchase_orders/dt','Admin\PurchaseOrderController@toDatatable')->name('purchase_orders.dt');
	Route::resource('purchase_orders', 'Admin\PurchaseOrderController');

	Route::get('reports/dt','Admin\ReportController@toDatatable')->name('reports.dt');
	Route::resource('reports', 'Admin\ReportController');

	Route::get('products/dt','Admin\ProductController@toDatatable')->name('products.dt');
	Route::resource('products', 'Admin\ProductController');
	
	Route::get('suplier_order/{supplier_order}/survey', 'Admin\SupplierOrderController@showSurvey')->name('supplier_orders.survey');

	Route::get('supplier_orders/to_calification', function(){})->name('supplier_orders.index_send_to_calification');
	Route::put('supplier_orders/to_calification/{supplier_order}','Admin\SupplierOrderController@sendToCalification')->name('supplier_orders.send_to_calification');
});

Route::get('orden/{purchase_order}', 'WebController@getPdf')->name('purchase_orders_pdf');

Route::get('preselection', function(){
	return view('admin.supplier_orders.preselection');
});

Route::get('supplier/create', 'Admin\SupplierController@supplierRegisterView')->name('supplier_external.register');
Route::get('supplier/register', 'Admin\SupplierController@supplierRegisterSuccess')->name('supplier_external.register.success');

app/Http/Controllers/Admin/PurchaseOrderController.php
<?php
namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\PurchaseOrder;

class PurchaseOrderController extends Controller
{

	/**
     * Instantiate a new controller instance.
     *
     * @return  void
     */
    public function __construct()
    {
        /* $this->middleware('permission:purchase_orders_create')->only(['store','create']);
        $this->middleware('permission:purchase_orders_read')->only(['index','show']);
        $this->middleware('permission:purchase_orders_update')->only(['update','edit']);
        $this->middleware('permission:purchase_orders_delete')->only(['delete']); */
    }

    /**
     * Display a listing of the resource in json format.
     *
     * @return  \Illuminate\Http\Response
     */
    public function toDatatable(Request $request)
    {
        $user= $request->user();
        $permissions=[
            'purchase_orders_read'=> true/* $user->hasPermissionTo('purchase_orders_read') */,
            'purchase_orders_update'=> true/* $user->hasPermissionTo('purchase_orders_update') */,
            'purchase_orders_delete'=> true/* $user->hasPermissionTo('purchase_orders_delete' )*/
        ];
        $purchase_orders = PurchaseOrder::all()->map(function($item) use($permissions){
            $items= [                
                [   
                    'permission'=>'purchase_orders_read',
                    'name'=>'Show',
                    'action'=>route('purchase_orders.show',['id'=>$item->id]),
                    'icon'=>'fa fa-eye',
                    'target'=>'_self',
                ],
                [
                    'permission'=>'purchase_orders_update',
                    'name'=>'Edit',
                    'action'=>route('purchase_orders.edit',['id'=>$item->id]),
                    'icon'=>'fa fa-edit',
                    'target'=>'_self',
                ],
                [
                    'permission'=>'purchase_orders_delete',
                    'name'=>'Delete', 
                    'data_id'=>$item->id,
                    'class_modal'=>'delete-modal',
                    'icon'=>'fa fa-trash-o',
                ],
            ];

            return[
                
                $item->id,
                $item->cotizacion,
                
                $item->fecha_orden,
                
                $item->fecha_pedido,
                
                $item->fecha_entrega,
                
                                view('settings.permissions', [
                    'items'=>$items,
                    'permissions'=>$permissions
                ])->render()
            ];
        })->all();
        return response()->json(['data'=> $purchase_orders ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return  \Illuminate\Http\Response
     */
    public function index()
    {
        
        $columns = "['Id','Cotizacion', 'Fecha Orden', 'Fecha Pedido', 'Fecha Entrega','Actions']";
        $link = 'purchase_orders.dt';
        return view('admin.purchase_orders.index', compact(['columns','link']));
        
    	//$purchase_orders = PurchaseOrder::all();
        //return view('admin.purchase_orders.index', compact(['purchase_orders']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return  \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.purchase_orders.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param    \Illuminate\Http\Request  $request
     * @return  \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([

	        'cotizacion'=> 'required|exists:quotations,id',
            'fecha_orden'=> 'required|date_format:"Y-m-d"',
            'fecha_pedido'=> 'required|date_format:"Y-m-d"',
            'fecha_entrega'=> 'required|date_format:"Y-m-d"',
            'observaciones'=> 'nullable|string',
            
	    ]);

	    $purchase_order = PurchaseOrder::create($request->all());

        $alert=[];
        $alert['status']= 'success';
        $alert['message']= trans('message.successfully_created');
		
		return redirect()->route('purchase_orders.index')->with('alert', $alert);
    }

    /**
     * Display the specified resource.
     *
     * @param    \App\PurchaseOrder  $purchase_order
     * @return  \Illuminate\Http\Response
     */
    public function show(Request $request, PurchaseOrder $purchase_order)
    {
        if (! $request->old()) {
            $request->replace($purchase_order->toArray());        
            $request->flash();
        }

        return view('admin.purchase_orders.show', compact(['purchase_order']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param    \App\PurchaseOrder  $purchase_order
     * @return  \Illuminate\Http\Response
     */
    public function edit(Request $request, PurchaseOrder $purchase_order)
    {
    	if (! $request->old()) {
            $request->replace($purchase_order->toArray());        
            $request->flash();
        }

    	return view('admin.purchase_orders.edit', compact(['purchase_order']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param    \Illuminate\Http\Request  $request
     * @param    \App\PurchaseOrder  $purchase_order
     * @return  \Illuminate\Http\Response
     */
    public function update(Request $request, PurchaseOrder $purchase_order)
    {
        $validatedData = $request->validate([

	        /* 'cotizacion'=> 'required|exists:quotations,id', */
            'fecha_orden'=> 'required|date_format:"Y-m-d"',
            'fecha_entrega'=> 'required|date_format:"Y-m-d"',
            'observaciones'=> 'nullable|string',
            
	    ]);

    	$purchase_order->fill($request->all())->save();

    	$alert=[];
        $alert['status']= 'success';
        $alert['message']= trans('message.successfully_updated');
	            
        return redirect()->route('supplier_orders.orders_index',['id'=>$purchase_order->quotation->supplierOrder->id])->with('alert', $alert);

                
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param    \App\PurchaseOrder  $purchase_order
     * @return  \Illuminate\Http\Response
     */
    public function destroy(PurchaseOrder $purchase_order)
    {
        $purchase_order->delete();

        $alert=[];
        $alert['status']= 'success';
        $alert['message']= trans('message.successfully_deleted');

        return redirect()->route('purchase_orders.index')->with('alert', $alert);
    }
}

resources/views/admin/purchase_orders/create.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	Ordenes De Compra
@endsection

@section('contentheader_title')
	Ordenes De Compra
@endsection

@section('contentheader_description')
	@lang('message.create')
@endsection

@section('main-content')
	<div class="row" id="sectionApp" v-cloak>
		<div class="col-md-12">
			@include('includes.session-alert')
			<form id="form-section" action="{{ route('purchase_orders.store') }}" method="POST" enctype="multipart/form-data" @submit.prevent="validateBeforeSubmit">
				<input type="hidden" name="_method" value="POST">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="row">
    				<div class="col-md-12">@include('HTML_VUE.input_text',[ 'label'=>'Cotizacion', 'placeholder'=>'Cotizacion', 'model'=>'cotizacion', 'name'=>"'cotizacion'", 'validate'=>"'required'"])</div>
    				<div class="col-md-12">@include('HTML_VUE.input_date',[ 'label'=>'Fecha Orden', 'placeholder'=>'Fecha Orden', 'model'=>'fecha_orden', 'name'=>"'fecha_orden'", 'validate'=>"'required'"])</div>
    				<div class="col-md-12">@include('HTML_VUE.input_date',[ 'label'=>'Fecha Pedido', 'placeholder'=>'Fecha Pedido', 'model'=>'fecha_pedido', 'name'=>"'fecha_pedido'", 'validate'=>"'required'"])</div>
    				<div class="col-md-12">@include('HTML_VUE.input_date',[ 'label'=>'Fecha Entrega', 'placeholder'=>'Fecha Entrega', 'model'=>'fecha_entrega', 'name'=>"'fecha_entrega'", 'validate'=>"'required'"])</div>
    				                    
                </div>
                <div class="row">
    				<div class="col-md-12">
    					<button type="submit" class="btn btn-primary">{{trans('message.create')}}</button>
    				</div>
                </div>
			</form>
		</div>
	</div>
@endsection

@section('local-css')
	<style type="text/css">
		[v-cloak] {
			display: none;
		}
		.grid-images-item{
            width: 100%;
            padding-top: 100%;
            border:solid 1px;
            background-size: contain;
            background-position: 50% 50%;
            background-repeat: no-repeat;
        }
        .container-sortable{
            background: transparent;
            border: 1px solid #3c8dbc;
            border-top: 3px solid #3c8dbc;
        }
	</style>
@endsection

@section('local-script')

    <!--<script src="http://requisitions.test/js/dist/locale/es.js" type="text/javascript"></script>
    <script src="http://requisitions.test/js/moment.min.js"></script>-->

    <script type="text/javascript">
        
        //Vue.use(VeeValidate, {locale:'es'});

        var section = new Vue({
            el: '#sectionApp',
            data: {

            	cotizacion:`{!!old('cotizacion')!!}` ,
                fecha_orden:`{!!old('fecha_orden')!!}` ,
                fecha_pedido:`{!!old('fecha_pedido')!!}` ,
                fecha_entrega:`{!!old('fecha_entrega')!!}` 
                
            },
            methods: {
            	
	            
	            
	            
	            
                validateBeforeSubmit() {
                    this.$validator.validateAll().then((result) => {
				        if (result) {
				          document.querySelector('#form-section').submit();
				          
				        }else{
				        	alert('Existen errores en el formulario!!!');
				        }
				    });
                },
                addGridImage(e){

                    var model= $(e.currentTarget).data('model');
                    var idx= $(e.currentTarget).data('idx');
                    var info= $(e.currentTarget).data('info');
                    if(idx!=undefined){
                        model= model.replace('index',idx);
                    }
                    console.log('model '+model);
                    console.log('idx '+idx);
                    var files = e.target.files || e.dataTransfer.files;
                    var vm = this;

                    for (var i = 0; i < files.length; i++) {
                        var reader = new FileReader();
                        reader.onload = function(e) {
                            var is_array;
                            eval('is_array= Array.isArray(vm.'+model+');');

                            if(is_array){
                                if(info!=undefined){
                                    console.log('info '+info);
                                    let data={
                                        image: e.target.result,
                                        text1:'',
                                        text2:'',
                                        text3:'',
                                    }
                                    eval('vm.'+model+".push(data);");
                                }else{
                                    eval('vm.'+model+".push(e.target.result);");
                                }
                            }else{
                                eval('vm.'+model+"= e.target.result;");
                            }
                        }
                        reader.readAsDataURL(files[i]);
                    }
                },
                removeGridImage(key,model,index=undefined){
                    console.log('key: '+key+' model: '+model+' index:'+index);
                    if(index != undefined){
                        model= model.replace('index',index);
                    }
                    eval('this.'+model+".splice(key,1);");
                    //this[model].splice(key,1);
                }
            },
            mounted(){
                $(document).on('change', '.input-image', this.addGridImage);
                $(document).on('click', '.box-header .box-tools button.sortable-button', function(){
                    $('i', this).toggleClass('fa-window-minimize');
                    $('i', this).toggleClass('fa-window-maximize');
                });
            }
        });

        //section.$validator.installDateTimeValidators(moment);
        
        @foreach($errors->toArray()?:[] as $key=>$value)
            section.errors.add('{{dot_to_html($key)}}', '{{$errors->first($key)}}');
        @endforeach
        
    </script>
    {{ session()->forget('_old_input') }}
@endsection

resources/views/admin/purchase_orders/edit.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	Ordenes De Compra
@endsection

@section('contentheader_title')
	Ordenes De Compra
@endsection

@section('contentheader_description')
	@lang('message.edit')
@endsection

@section('main-content')
	<div class="row" id="sectionApp" v-cloak>
		<div class="col-md-12">
			@include('includes.session-alert')
			<form id="form-section" action="{{ route('purchase_orders.update', $purchase_order->id) }}" method="POST" enctype="multipart/form-data" @submit.prevent="validateBeforeSubmit">
				<input type="hidden" name="_method" value="PUT">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="row">
    				{{-- <div class="col-md-12">@include('HTML_VUE.input_text',[ 'label'=>'Cotizacion', 'placeholder'=>'Cotizacion', 'model'=>'cotizacion', 'name'=>"'cotizacion'", 'validate'=>"'required'"])</div> --}}
    				<div class="col-md-12">@include('HTML_VUE.input_date',[ 'label'=>'Fecha Orden', 'placeholder'=>'Fecha Orden', 'model'=>'fecha_orden', 'name'=>"'fecha_orden'", 'validate'=>"'required'"])</div>
    				{{--<div class="col-md-12">@include('HTML_VUE.input_date',[ 'label'=>'Fecha Pedido', 'placeholder'=>'Fecha Pedido', 'model'=>'fecha_pedido', 'name'=>"'fecha_pedido'", 'validate'=>"'required'"])</div>--}}
    				<div class="col-md-12">@include('HTML_VUE.input_date',[ 'label'=>'Fecha Entrega', 'placeholder'=>'Fecha Entrega', 'model'=>'fecha_entrega', 'name'=>"'fecha_entrega'", 'validate'=>"'required'"])</div>
    				                    
                </div>
                <div class="row">
                    <div class="col-md-12">@include('HTML_VUE.input_text',[ 'label'=>'Observaciones', 'placeholder'=>'Observaciones', 'model'=>'observaciones', 'name'=>"'observaciones'", 'validate'=>"''"])</div>
                </div>
                <div class="row">
    				<div class="col-md-12">
    					<button type="submit" class="btn btn-primary">{{trans('message.edit')}}</button>
    				</div>
                </div>
			</form>
		</div>
	</div>
@endsection

@section('local-css')
	<style type="text/css">
		[v-cloak] {
			display: none;
		}
		.grid-images-item{
            width: 100%;
            padding-top: 100%;
            border:solid 1px;
            background-size: contain;
            background-position: 50% 50%;
            background-repeat: no-repeat;
        }
        .container-sortable{
            background: transparent;
            border: 1px solid #3c8dbc;
            border-top: 3px solid #3c8dbc;
        }
	</style>
@endsection

@section('local-script')

    <!--<script src="http://requisitions.test/js/dist/locale/es.js" type="text/javascript"></script>
    <script src="http://requisitions.test/js/moment.min.js"></script>-->

    <script type="text/javascript">
        
        //Vue.use(VeeValidate, {locale:'es'});

        var section = new Vue({
            el: '#sectionApp',
            data: {

            	/* cotizacion:`{!!old('cotizacion')!!}` , */
                /* fecha_pedido:`{!!old('fecha_pedido')!!}` ,*/
                fecha_orden:`{!!old('fecha_orden')!!}` ,
                fecha_entrega:`{!!old('fecha_entrega')!!}`,
                observaciones:`{!!old('observaciones')!!}` 
                
            },
            methods: {
                validateBeforeSubmit() {
                    this.$validator.validateAll().then((result) => {
				        if (result) {
				          document.querySelector('#form-section').submit();
				          
				        }else{
				        	alert('Existen errores en el formulario!!!');
				        }
				    });
                },
                addGridImage(e){

                    var model= $(e.currentTarget).data('model');
                    var idx= $(e.currentTarget).data('idx');
                    var info= $(e.currentTarget).data('info');
                    if(idx!=undefined){
                        model= model.replace('index',idx);
                    }
                    console.log('model '+model);
                    console.log('idx '+idx);
                    var files = e.target.files || e.dataTransfer.files;
                    var vm = this;

                    for (var i = 0; i < files.length; i++) {
                        var reader = new FileReader();
                        reader.onload = function(e) {
                            var is_array;
                            eval('is_array= Array.isArray(vm.'+model+');');

                            if(is_array){
                                if(info!=undefined){
                                    console.log('info '+info);
                                    let data={
                                        image: e.target.result,
                                        text1:'',
                                        text2:'',
                                        text3:'',
                                    }
                                    eval('vm.'+model+".push(data);");
                                }else{
                                    eval('vm.'+model+".push(e.target.result);");
                                }
                            }else{
                                eval('vm.'+model+"= e.target.result;");
                            }
                        }
                        reader.readAsDataURL(files[i]);
                    }
                },
                removeGridImage(key,model,index=undefined){
                    console.log('key: '+key+' model: '+model+' index:'+index);
                    if(index != undefined){
                        model= model.replace('index',index);
                    }
                    eval('this.'+model+".splice(key,1);");
                    //this[model].splice(key,1);
                }
            },
            mounted(){
                $(document).on('change', '.input-image', this.addGridImage);
                $(document).on('click', '.box-header .box-tools button.sortable-button', function(){
                    $('i', this).toggleClass('fa-window-minimize');
                    $('i', this).toggleClass('fa-window-maximize');
                });
            }
        });

        //section.$validator.installDateTimeValidators(moment);
        
        @foreach($errors->toArray()?:[] as $key=>$value)
            section.errors.add('{{dot_to_html($key)}}', '{{$errors->first($key)}}');
        @endforeach
        
    </script>
    {{ session()->forget('_old_input') }}
@endsection

resources/views/admin/purchase_orders/index.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	Ordenes De Compra
@endsection

@section('contentheader_title')
    Ordenes De Compra
@endsection

@section('contentheader_description')
    @lang('message.index')
@endsection

@section('main-content')	
	<div class="row" id="sectionApp">
		<div class="col-md-12">
			@include('includes.session-alert')

            <datatable :columns="{!!$columns!!}" 
            			:url="'{!! route($link) !!}'"
            			:is-unique="false">
            </datatable>
		</div>
        <div class="col-md-12">@include('includes.button-create',['permission'=>'purchase_orders_create', 'url'=>route('purchase_orders.create')])</div>
        @include('includes.delete-modal',['permission'=>'purchase_orders_delete'])
	</div>
@endsection
@section('local-script')

    <!--<script src="http://requisitions.test/js/dist/locale/es.js" type="text/javascript"></script>
    <script src="http://requisitions.test/js/moment.min.js"></script>-->

    <script type="text/javascript">
        
        //Vue.use(VeeValidate, {locale:'es'});

        var section = new Vue({
            el: '#sectionApp',
            data:{
                base_url: '{{route('purchase_orders.index')}}',
                to_delete: null
            },
            methods:{
                delete(e){
                    var id= $(e.currentTarget).data('id');
                    this.to_delete= id;
                    console.log(this.to_delete);
                    $('#deleteModal').modal('show');
                },
            },
            mounted(){
                $(document).on("click",".delete-modal", this.delete);
            }
        });

        //section.$validator.installDateTimeValidators(moment);
        
    </script>
    {{ session()->forget('_old_input') }}
@endsection