routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('register', function(){
	return redirect('/login');
});
Route::post('register', function(){
	return redirect('/login');
});

Route::get('/', function () {
    return redirect('/login');
});

Route::get('files/{file}','WebController@file');

Route::group(['middleware' => 'auth'], function () {
    //    Route::get('/link1', function ()    {
//        // Uses Auth Middleware
//    });

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
});


Route::middleware(['auth'])->prefix('admin')->group(function(){
	
	Route::get('sections/only-create','Admin\SectionController@onlyCreate')->name('sections.only-create');
	Route::post('sections/only-store','Admin\SectionController@onlyStore')->name('sections.only-store');
	Route::get('sections/dt','Admin\SectionController@toDatatable')->name('sections.dt');
	Route::resource('sections', 'Admin\SectionController');

    Route::get('users/dt','Admin\UserController@toDatatable')->name('users.dt');
    Route::resource('users', 'Admin\UserController');
    
    Route::get('permissions/dt','Admin\PermissionController@toDatatable')->name('permissions.dt');
    Route::resource('permissions', 'Admin\PermissionController');
    
    Route::get('roles/dt','Admin\RoleController@toDatatable')->name('roles.dt');
    Route::resource('roles', 'Admin\RoleController');

    Route::get('administrative_areas/dt','Admin\AdministrativeAreaController@toDatatable')->name('administrative_areas.dt');
	Route::resource('administrative_areas', 'Admin\AdministrativeAreaController');
	
	Route::get('operative_areas/dt','Admin\OperativeAreaController@toDatatable')->name('operative_areas.dt');
	Route::resource('operative_areas', 'Admin\OperativeAreaController');
	
	Route::get('payment_methods/dt','Admin\PaymentMethodController@toDatatable')->name('payment_methods.dt');
	Route::resource('payment_methods', 'Admin\PaymentMethodController');

	Route::get('experience_ranges/dt','Admin\ExperienceRangeController@toDatatable')->name('experience_ranges.dt');
	Route::resource('experience_ranges', 'Admin\ExperienceRangeController');
	
	Route::get('suppliers/dt','Admin\SupplierController@toDatatable')->name('suppliers.dt');
	Route::get('suppliers/invitation','Admin\SupplierController@formInvitation')->name('suppliers.form_invitation');
	Route::post('suppliers/invitation','Admin\SupplierController@sendInvitation')->name('suppliers.send_invitation');
	Route::get('suppliers/{supplier}/products','Admin\SupplierController@formProducts')->name('supplier.edit_products');
	Route::post('suppliers/{supplier}/products','Admin\SupplierController@updateProducts')->name('supplier.update_products');
	Route::resource('suppliers', 'Admin\SupplierController');

	/*RUTAS PARA LA ORDENES DE PROVEEDORES*/
	Route::get('supplier_orders/{supplier_order}/ordenes_json','Admin\SupplierOrderController@orderJson')->name('supplier_orders.orders_json');
	Route::get('supplier_orders/{supplier_order}/ordenes','Admin\SupplierOrderController@listOrder')->name('supplier_orders.orders_index');

	Route::get('supplier_orders/create_order/{supplier_order}','Admin\SupplierOrderController@formCreateOrder')->name('supplier_orders.form_order');
	Route::put('supplier_orders/create_order/{supplier_order}','Admin\SupplierOrderController@storeOrder')->name('supplier_orders.store_order');
	
	Route::get('supplier_orders/selection_matrix/{supplier_order}','Admin\SupplierOrderController@selectionMatrix')->name('supplier_orders.selection_matrix');
	Route::get('supplier_orders/observaciones/{supplier_order}','Admin\SupplierOrderController@observaciones')->name('supplier_orders.observaciones');
	Route::get('supplier_orders/cotizaciones/{supplier_order}','Admin\SupplierOrderController@cotizaciones')->name('supplier_orders.cotizaciones');

	Route::get('supplier_orders/requisition/dt','Admin\SupplierOrderController@toDatatableRequisition')->name('supplier_orders.dt_requisition');
	Route::get('supplier_orders/requisition','Admin\SupplierOrderController@indexRequisition')->name('supplier_orders.index_requisition');
	Route::get('supplier_orders/requisition/create','Admin\SupplierOrderController@createRequisition')->name('supplier_orders.create_requisition');
	Route::post('supplier_orders/requisition','Admin\SupplierOrderController@storeRequisition')->name('supplier_orders.store_requisition');

	Route::get('supplier_orders/requisition/pdf/{supplier_order}','Admin\SupplierOrderController@pdfRequisition')->name('supplier_orders.pdf_requisition');

	Route::get('supplier_orders/autorization/dt','Admin\SupplierOrderController@toDatatableAutorization')->name('supplier_orders.dt_autorization');
	Route::get('supplier_orders/autorization','Admin\SupplierOrderController@indexAutorization')->name('supplier_orders.index_autorization');
	Route::get('supplier_orders/autorization/{supplier_order}/edit','Admin\SupplierOrderController@editAutorization')->name('supplier_orders.edit_autorization');
	Route::put('supplier_orders/autorization/{supplier_order}','Admin\SupplierOrderController@updateAutorization')->name('supplier_orders.update_autorization');
	Route::get('supplier_orders/autorization/{supplier_order}/reject','Admin\SupplierOrderController@rejectAutorization')->name('supplier_orders.reject_autorization');
	Route::put('supplier_orders/autorization/{supplier_order}/refuse','Admin\SupplierOrderController@refuseAutorization')->name('supplier_orders.refuse_autorization');
	Route::get('supplier_orders/autorization/{supplier_order}/pause','Admin\SupplierOrderController@pauseAutorization')->name('supplier_orders.pause_autorization');
	Route::put('supplier_orders/autorization/{supplier_order}/stop','Admin\SupplierOrderController@stopAutorization')->name('supplier_orders.stop_autorization');

	Route::get('supplier_orders/quotation/dt','Admin\SupplierOrderController@toDatatableQuotation')->name('supplier_orders.dt_quotation');
	Route::get('supplier_orders/quotation','Admin\SupplierOrderController@indexQuotation')->name('supplier_orders.index_quotation');
	Route::get('supplier_orders/quotation/{supplier_order}/edit','Admin\SupplierOrderController@editQuotation')->name('supplier_orders.edit_quotation');
	Route::put('supplier_orders/quotation/{supplier_order}','Admin\SupplierOrderController@updateQuotation')->name('supplier_orders.update_quotation');

	Route::get('supplier_orders/regenerate/{supplier_order}','Admin\SupplierOrderController@regenerateGet')->name('supplier_orders.regenerate_get');
	Route::put('supplier_orders/regenerate/{supplier_order}','Admin\SupplierOrderController@regeneratePut')->name('supplier_orders.regenerate_put');

	Route::get('supplier_orders/supplier_quote/dt','Admin\SupplierOrderController@toDatatableSupplierQuote')->name('supplier_orders.dt_supplier_quote');
	Route::get('supplier_orders/supplier_quote','Admin\SupplierOrderController@indexSupplierQuote')->name('supplier_orders.index_supplier_quote');
	Route::get('supplier_orders/supplier_quote/{quotation}/edit','Admin\SupplierOrderController@editSupplierQuote')->name('supplier_orders.edit_supplier_quote');
	Route::put('supplier_orders/supplier_quote/{quotation}','Admin\SupplierOrderController@updateSupplierQuote')->name('supplier_orders.update_supplier_quote');

	Route::get('supplier_orders/preselection/dt','Admin\SupplierOrderController@toDatatablePreselection')->name('supplier_orders.dt_preselection');
	Route::get('supplier_orders/preselection','Admin\SupplierOrderController@indexPreselection')->name('supplier_orders.index_preselection');
	Route::get('supplier_orders/preselection/{supplier_order}/edit','Admin\SupplierOrderController@editPreselection')->name('supplier_orders.edit_preselection');
	Route::put('supplier_orders/preselection/{supplier_order}','Admin\SupplierOrderController@updatePreselection')->name('supplier_orders.update_preselection');

	Route::get('supplier_orders/preselection/pdf/{purchase_order}','Admin\SupplierOrderController@pdfPurchaseOrder')->name('supplier_orders.pdf_purchase_order');

	Route::get('supplier_orders/send/dt','Admin\SupplierOrderController@toDatatableSend')->name('supplier_orders.dt_send');
	Route::get('supplier_orders/send','Admin\SupplierOrderController@indexSend')->name('supplier_orders.index_send');
	//Route::get('supplier_orders/send/{supplier_order}/edit','Admin\SupplierOrderController@editSend')->name('supplier_orders.edit_send');
	Route::put('supplier_orders/send/{supplier_order}','Admin\SupplierOrderController@updateSend')->name('supplier_orders.update_send');

	Route::get('supplier_orders/score/dt','Admin\SupplierOrderController@toDatatableScore')->name('supplier_orders.dt_score');
	Route::get('supplier_orders/score','Admin\SupplierOrderController@indexScore')->name('supplier_orders.index_score');
	Route::get('supplier_orders/score/{supplier_order}/edit','Admin\SupplierOrderController@editScore')->name('supplier_orders.edit_score');
	Route::put('supplier_orders/score/{supplier_order}','Admin\SupplierOrderController@updateScore')->name('supplier_orders.update_score');


	Route::get('supplier_orders/dt','Admin\SupplierOrderController@toDatatable')->name('supplier_orders.dt');
	Route::resource('supplier_orders', 'Admin\SupplierOrderController');

	/***************************************/

	Route::get('order_priorities/dt','Admin\OrderPriorityController@toDatatable')->name('order_priorities.dt');
	Route::resource('order_priorities', 'Admin\OrderPriorityController');

	Route::get('measurement_units/dt','Admin\MeasurementUnitController@toDatatable')->name('measurement_units.dt');

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Supplier extends Model
{
    use SoftDeletes;

    protected $table = 'suppliers';
    protected $fillable = ['informacion_general', 'informacion_de_la_empresa', 'clase_de_proveedor', 'sector_economico', 'informacion_tributaria', 'informacion_financiera', 'documentos_requeridos'];
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];
    protected $casts = [
        'informacion_general' => 'array',
        'informacion_de_la_empresa' => 'array',
        'clase_de_proveedor' => 'array',
        'sector_economico' => 'array',
        'informacion_tributaria' => 'array',
        'informacion_financiera' => 'array',
        'documentos_requeridos' => 'array',
    ];

    public function users()
    {
        return $this->morphToMany('App\User', 'userable');
    }


    public function quotations()
    {
        return $this->hasMany('App\Quotation', 'proveedor');
    }

    public function products()
    {
        return $this->belongsToMany('App\Product', 'product_supplier', 'supplier_id', 'product_id');
    }

    public function areas()
    {
        return $this->belongsToMany('App\OperativeArea', 'operative_area_supplier', 'supplier_id', 'operative_area_id');
    }

    public function getEmail()
    {
        return array_get($this->informacion_general, 'email', '');
    }

    public function productsToString()
    {
        $items = array_pluck($this->products ?: [], 'nombre');

        return  implode(', ', $items);
    }

    public function areasToString()
    {
        $items = array_pluck($this->areas ?: [], 'nombre');

        return  implode(', ', $items);
    }
}

resources/views/admin/suppliers/index.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	Proveedores
@endsection

@section('contentheader_title')
    Proveedores
@endsection

@section('contentheader_description')
    @lang('message.index')
@endsection

@section('main-content')	
	<div class="row" id="sectionApp">
		<div class="col-md-12">
			@include('includes.session-alert')

            <datatable :columns="{!!$columns!!}" 
            			:url="'{!! route($link) !!}'"
            			:is-unique="false">
            </datatable>
		</div>
        <div class="col-md-12">
            @include('includes.button-create',['permission'=>'suppliers_create', 'url'=>route('suppliers.create')])
            <a class="btn btn-success" href="{!!route('suppliers.form_invitation')!!}" role="button">Enviar Invitación</a>
            <a class="btn btn-primary" target="_blank" href="{!!route('supplier_external.register')!!}" role="button">Registrar Proveedor</a>
        </div>
        @include('includes.delete-modal',['permission'=>'suppliers_delete'])
	</div>
@endsection
@section('local-script')

    <!--<script src="http://liceo_compras.test/js/dist/locale/es.js" type="text/javascript"></script>
    <script src="http://liceo_compras.test/js/moment.min.js"></script>-->

    <script type="text/javascript">
        
        //Vue.use(VeeValidate, {locale:'es'});

        var section = new Vue({
            el: '#sectionApp',
            data:{
                base_url: '{{route('suppliers.index')}}',
                to_delete: null
            },
            methods:{
                delete(e){
                    var id= $(e.currentTarget).data('id');
                    this.to_delete= id;
                    console.log(this.to_delete);
                    $('#deleteModal').modal('show');
                },
            },
            mounted(){
                $(document).on("click",".delete-modal", this.delete);
            }
        });

        //section.$validator.installDateTimeValidators(moment);
        
    </script>
    {{ session()->forget('_old_input') }}
@endsection

resources/views/admin/suppliers/invitation.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	Proveedores
@endsection

@section('contentheader_title')
	Proveedores
@endsection

@section('contentheader_description')
	Enviar Invitación
@endsection

@section('main-content')
	<div class="row" id="sectionApp" v-cloak>
		<div class="col-md-12">
			@include('includes.session-alert')
			<form id="form-section" action="{{ route('suppliers.send_invitation') }}" method="POST" enctype="multipart/form-data" @submit.prevent="validateBeforeSubmit">
				<input type="hidden" name="_method" value="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                
                <div class="row">
                    <div class="col-md-12">
                        <div class="box box-primary container-sortable">
                            <div class="box-header with-border">
                                <h3 class="box-title">Lista de emails</h3>
                                <div class="box-tools pull-right">
                                    <button type="button" class="btn btn-primary btn-xs" v-on:click="addEmail()">Añadir Email</button>                                    
                                </div>
                            </div>
                            <div class="box-body">                                
                                <div v-for="(item, index) in emails" class="box">
                                    <div class="box-header with-border">
                                        <h3 class="box-title">
                                            Email                                           
                                        </h3>
                                        <div class="box-tools pull-right">
                                            <button type="button" class="btn btn-box-tool" title="Remove" v-on:click="removeEmail(index)"><i class="fa fa-times"></i></button>
                                        </div>
                                    </div>
                                    <div class="box-body" :id="'emails_'+index">
                                        <div class="row">
                                            <div class="col-md-12">@include('HTML_VUE.input_text',['model'=>"emails[index]", 'name'=>"'emails['+index+']'", 'placeholder'=>'Email', 'validate'=>"'required|email'"])</div>
                                        </div>
                                    </div>
                                </div>                                
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
    				<div class="col-md-12">
    					<button type="submit" class="btn btn-primary">Enviar Invitación</button>
    				</div>
                </div>
			</form>
		</div>
	</div>
@endsection

@section('local-css')
	<style type="text/css">
		[v-cloak] {
			display: none;
		}
		.grid-images-item{
            width: 100%;
            padding-top: 100%;
            border:solid 1px;
            background-size: contain;
            background-position: 50% 50%;
            background-repeat: no-repeat;
        }
        .container-sortable{
            background: transparent;
            border: 1px solid #3c8dbc;
            border-top: 3px solid #3c8dbc;
        }
	</style>
@endsection

@section('local-script')

    <!--<script src="http://liceo_compras.test/js/dist/locale/es.js" type="text/javascript"></script>
    <script src="http://liceo_compras.test/js/moment.min.js"></script>-->

    <script type="text/javascript">
        
        //Vue.use(VeeValidate, {locale:'es'});

        var section = new Vue({
            el: '#sectionApp',
            data: {
                emails: ['']                
            },
            methods: {
                addEmail(){
                    this.emails.push('');
                },
                removeEmail(index){
                    this.emails.splice(index,1);
                },
                validateBeforeSubmit() {
                    this.$validator.validateAll().then((result) => {
				        if (result) {
				          document.querySelector('#form-section').submit();
				          
				        }else{
				        	alert('Existen errores en el formulario!!!');
				        }
				    });
                }
            },
            mounted(){
            }
        });

        //section.$validator.installDateTimeValidators(moment);
        
        @foreach($errors->toArray()?:[] as $key=>$value)
            section.errors.add('{{dot_to_html($key)}}', '{{$errors->first($key)}}');
        @endforeach
        
    </script>
    {{ session()->forget('_old_input') }}
@endsection

resources/views/admin/suppliers/products.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	Proveedores 
@endsection

@section('contentheader_title')
	Proveedores 
@endsection

@section('contentheader_description')
	Productos
@endsection

@section('main-content')
	<div class="row" id="sectionApp" v-cloak>
		<div class="col-md-12">
			@include('includes.session-alert')
			<form id="form-section" action="{{ route('supplier.update_products', $supplier->id) }}" method="POST" enctype="multipart/form-data" @submit.prevent="validateBeforeSubmit">
				<input type="hidden" name="_method" value="POST">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="row">
                	<div class="col-md-12">
                        <div class="form-group" :class="{'has-error': errors.has('products') }">
                            <label class="control-label">Productos</label>
                            <v-select multiple v-validate="'required'" v-model="products" :options="products_options" label="nombre" placeholder="Seleccionar Productos"></v-select>
                            <input v-for="product in products" type="hidden" name="products[]" v-bind:value="product.id">
                            <span class="help-block" v-if="errors.has('products')">@{{errors.first('products')}}</span>                            
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-group" :class="{'has-error': errors.has('areas') }">
                            <label class="control-label">Areas</label>
                            <v-select multiple v-validate="'required'" v-model="areas" :options="areas_options" label="nombre" placeholder="Seleccionar Areas"></v-select>
                            <input v-for="area in areas" type="hidden" name="areas[]" v-bind:value="area.id">
                            <span class="help-block" v-if="errors.has('areas')">@{{errors.first('areas')}}</span>                            
                        </div>
                    </div>
                </div>
                <div class="row">
    				<div class="col-md-12">
    					<button type="submit" class="btn btn-primary">Guardar</button>
    				</div>
                </div>
			</form>
		</div>
	</div>
@endsection

@section('local-css')
	<style type="text/css">
		[v-cloak] {
			display: none;
		}
		.grid-images-item{
            width: 100%;
            padding-top: 100%;
            border:solid 1px;
            background-size: contain;
            background-position: 50% 50%;
            background-repeat: no-repeat;
        }
        .container-sortable{
            background: transparent;
            border: 1px solid #3c8dbc;
            border-top: 3px solid #3c8dbc;
        }

        .v-select .dropdown-toggle {
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
            display: flex;
            padding: 0 0 4px;
            background: none;
            border: 1px solid rgba(60,60,60,.26);
            border-radius: 0 !important;
            white-space: normal;
        }
	</style>
@endsection

@section('local-script')

    <!--<script src="http://liceo_compras.test/js/dist/locale/es.js" type="text/javascript"></script>
    <script src="http://liceo_compras.test/js/moment.min.js"></script>-->
	<script src="https://unpkg.com/vue-select@2.5.1/dist/vue-select.js"></script>
    <script type="text/javascript">
        
        //Vue.use(VeeValidate, {locale:'es'});
        Vue.component('v-select', VueSelect.VueSelect);

        var section = new Vue({
            el: '#sectionApp',
            data: {
                products: {!!old('products')!!} ,
                products_options: {!!$products_options!!},
                areas: {!!old('areas')!!},
                areas_options: {!!$areas_options!!}                
            },
            methods: {	            
                validateBeforeSubmit() {
                    this.$validator.validateAll().then((result) => {
				        if (result) {
				          document.querySelector('#form-section').submit();
				          
				        }else{
				        	alert('Existen errores en el formulario!!!');
				        }
				    });
                }
            },
            mounted(){
            }
        });

        //section.$validator.installDateTimeValidators(moment);
        
        @foreach($errors->toArray()?:[] as $key=>$value)
            section.errors.add('{{dot_to_html($key)}}', '{{$errors->first($key)}}');
        @endforeach
        
    </script>
    {{ session()->forget('_old_input') }}
@endsection