routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('register', function(){
	return redirect('/login');
});
Route::post('register', function(){
	return redirect('/login');
});

Route::get('/', function () {
    return redirect('/login');
});

Route::get('files/{file}','WebController@file');

Route::group(['middleware' => 'auth'], function () {
    //    Route::get('/link1', function ()    {
//        // Uses Auth Middleware
//    });

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
});


Route::middleware(['auth'])->prefix('admin')->group(function(){
	
	Route::get('sections/only-create','Admin\SectionController@onlyCreate')->name('sections.only-create');
	Route::post('sections/only-store','Admin\SectionController@onlyStore')->name('sections.only-store');
	Route::get('sections/dt','Admin\SectionController@toDatatable')->name('sections.dt');
	Route::resource('sections', 'Admin\SectionController');

    Route::get('users/dt','Admin\UserController@toDatatable')->name('users.dt');
    Route::resource('users', 'Admin\UserController');
    
    Route::get('permissions/dt','Admin\PermissionController@toDatatable')->name('permissions.dt');
    Route::resource('permissions', 'Admin\PermissionController');
    
    Route::get('roles/dt','Admin\RoleController@toDatatable')->name('roles.dt');
    Route::resource('roles', 'Admin\RoleController');

    Route::get('administrative_areas/dt','Admin\AdministrativeAreaController@toDatatable')->name('administrative_areas.dt');
	Route::resource('administrative_areas', 'Admin\AdministrativeAreaController');
	
	Route::get('operative_areas/dt','Admin\OperativeAreaController@toDatatable')->name('operative_areas.dt');
	Route::resource('operative_areas', 'Admin\OperativeAreaController');
	
	Route::get('payment_methods/dt','Admin\PaymentMethodController@toDatatable')->name('payment_methods.dt');
	Route::resource('payment_methods', 'Admin\PaymentMethodController');

	Route::get('experience_ranges/dt','Admin\ExperienceRangeController@toDatatable')->name('experience_ranges.dt');
	Route::resource('experience_ranges', 'Admin\ExperienceRangeController');
	
	Route::get('suppliers/dt','Admin\SupplierController@toDatatable')->name('suppliers.dt');
	Route::get('suppliers/invitation','Admin\SupplierController@formInvitation')->name('suppliers.form_invitation');
	Route::post('suppliers/invitation','Admin\SupplierController@sendInvitation')->name('suppliers.send_invitation');
	Route::get('suppliers/{supplier}/products','Admin\SupplierController@formProducts')->name('supplier.edit_products');
	Route::post('suppliers/{supplier}/products','Admin\SupplierController@updateProducts')->name('supplier.update_products');
	Route::resource('suppliers', 'Admin\SupplierController');

	/*RUTAS PARA LA ORDENES DE PROVEEDORES*/
	Route::get('supplier_orders/{supplier_order}/ordenes_json','Admin\SupplierOrderController@orderJson')->name('supplier_orders.orders_json');
	Route::get('supplier_orders/{supplier_order}/ordenes','Admin\SupplierOrderController@listOrder')->name('supplier_orders.orders_index');

	Route::get('supplier_orders/create_order/{supplier_order}','Admin\SupplierOrderController@formCreateOrder')->name('supplier_orders.form_order');
	Route::put('supplier_orders/create_order/{supplier_order}','Admin\SupplierOrderController@storeOrder')->name('supplier_orders.store_order');
	
	Route::get('supplier_orders/selection_matrix/{supplier_order}','Admin\SupplierOrderController@selectionMatrix')->name('supplier_orders.selection_matrix');
	Route::get('supplier_orders/observaciones/{supplier_order}','Admin\SupplierOrderController@observaciones')->name('supplier_orders.observaciones');
	Route::get('supplier_orders/cotizaciones/{supplier_order}','Admin\SupplierOrderController@cotizaciones')->name('supplier_orders.cotizaciones');

	Route::get('supplier_orders/requisition/dt','Admin\SupplierOrderController@toDatatableRequisition')->name('supplier_orders.dt_requisition');
	Route::get('supplier_orders/requisition','Admin\SupplierOrderController@indexRequisition')->name('supplier_orders.index_requisition');
	Route::get('supplier_orders/requisition/create','Admin\SupplierOrderController@createRequisition')->name('supplier_orders.create_requisition');
	Route::post('supplier_orders/requisition','Admin\SupplierOrderController@storeRequisition')->name('supplier_orders.store_requisition');

	Route::get('supplier_orders/requisition/pdf/{supplier_order}','Admin\SupplierOrderController@pdfRequisition')->name('supplier_orders.pdf_requisition');

	Route::get('supplier_orders/autorization/dt','Admin\SupplierOrderController@toDatatableAutorization')->name('supplier_orders.dt_autorization');
	Route::get('supplier_orders/autorization','Admin\SupplierOrderController@indexAutorization')->name('supplier_orders.index_autorization');
	Route::get('supplier_orders/autorization/{supplier_order}/edit','Admin\SupplierOrderController@editAutorization')->name('supplier_orders.edit_autorization');
	Route::put('supplier_orders/autorization/{supplier_order}','Admin\SupplierOrderController@updateAutorization')->name('supplier_orders.update_autorization');
	Route::get('supplier_orders/autorization/{supplier_order}/reject','Admin\SupplierOrderController@rejectAutorization')->name('supplier_orders.reject_autorization');
	Route::put('supplier_orders/autorization/{supplier_order}/refuse','Admin\SupplierOrderController@refuseAutorization')->name('supplier_orders.refuse_autorization');
	Route::get('supplier_orders/autorization/{supplier_order}/pause','Admin\SupplierOrderController@pauseAutorization')->name('supplier_orders.pause_autorization');
	Route::put('supplier_orders/autorization/{supplier_order}/stop','Admin\SupplierOrderController@stopAutorization')->name('supplier_orders.stop_autorization');

	Route::get('supplier_orders/quotation/dt','Admin\SupplierOrderController@toDatatableQuotation')->name('supplier_orders.dt_quotation');
	Route::get('supplier_orders/quotation','Admin\SupplierOrderController@indexQuotation')->name('supplier_orders.index_quotation');
	Route::get('supplier_orders/quotation/{supplier_order}/edit','Admin\SupplierOrderController@editQuotation')->name('supplier_orders.edit_quotation');
	Route::put('supplier_orders/quotation/{supplier_order}','Admin\SupplierOrderController@updateQuotation')->name('supplier_orders.update_quotation');

	Route::get('supplier_orders/regenerate/{supplier_order}','Admin\SupplierOrderController@regenerateGet')->name('supplier_orders.regenerate_get');
	Route::put('supplier_orders/regenerate/{supplier_order}','Admin\SupplierOrderController@regeneratePut')->name('supplier_orders.regenerate_put');

	Route::get('supplier_orders/supplier_quote/dt','Admin\SupplierOrderController@toDatatableSupplierQuote')->name('supplier_orders.dt_supplier_quote');
	Route::get('supplier_orders/supplier_quote','Admin\SupplierOrderController@indexSupplierQuote')->name('supplier_orders.index_supplier_quote');
	Route::get('supplier_orders/supplier_quote/{quotation}/edit','Admin\SupplierOrderController@editSupplierQuote')->name('supplier_orders.edit_supplier_quote');
	Route::put('supplier_orders/supplier_quote/{quotation}','Admin\SupplierOrderController@updateSupplierQuote')->name('supplier_orders.update_supplier_quote');

	Route::get('supplier_orders/preselection/dt','Admin\SupplierOrderController@toDatatablePreselection')->name('supplier_orders.dt_preselection');
	Route::get('supplier_orders/preselection','Admin\SupplierOrderController@indexPreselection')->name('supplier_orders.index_preselection');
	Route::get('supplier_orders/preselection/{supplier_order}/edit','Admin\SupplierOrderController@editPreselection')->name('supplier_orders.edit_preselection');
	Route::put('supplier_orders/preselection/{supplier_order}','Admin\SupplierOrderController@updatePreselection')->name('supplier_orders.update_preselection');

	Route::get('supplier_orders/preselection/pdf/{purchase_order}','Admin\SupplierOrderController@pdfPurchaseOrder')->name('supplier_orders.pdf_purchase_order');

	Route::get('supplier_orders/send/dt','Admin\SupplierOrderController@toDatatableSend')->name('supplier_orders.dt_send');
	Route::get('supplier_orders/send','Admin\SupplierOrderController@indexSend')->name('supplier_orders.index_send');
	//Route::get('supplier_orders/send/{supplier_order}/edit','Admin\SupplierOrderController@editSend')->name('supplier_orders.edit_send');
	Route::put('supplier_orders/send/{supplier_order}','Admin\SupplierOrderController@updateSend')->name('supplier_orders.update_send');

	Route::get('supplier_orders/score/dt','Admin\SupplierOrderController@toDatatableScore')->name('supplier_orders.dt_score');
	Route::get('supplier_orders/score','Admin\SupplierOrderController@indexScore')->name('supplier_orders.index_score');
	Route::get('supplier_orders/score/{supplier_order}/edit','Admin\SupplierOrderController@editScore')->name('supplier_orders.edit_score');
	Route::put('supplier_orders/score/{supplier_order}','Admin\SupplierOrderController@updateScore')->name('supplier_orders.update_score');


	Route::get('supplier_orders/dt','Admin\SupplierOrderController@toDatatable')->name('supplier_orders.dt');
	Route::resource('supplier_orders', 'Admin\SupplierOrderController');

	/***************************************/

	Route::get('order_priorities/dt','Admin\OrderPriorityController@toDatatable')->name('order_priorities.dt');
	Route::resource('order_priorities', 'Admin\OrderPriorityController');

	Route::get('measurement_units/dt','Admin\MeasurementUnitController@toDatatable')->name('measurement_units.dt');

app/Http/Controllers/Admin/OperativeAreaController.php
<?php
namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\OperativeArea, App\AdministrativeArea, App\User;

class OperativeAreaController extends Controller
{

	/**
     * Instantiate a new controller instance.
     *
     * @return  void
     */
    public function __construct()
    {
        $this->middleware('permission:operative_areas_create')->only(['store','create']);
        $this->middleware('permission:operative_areas_read')->only(['index','show']);
        $this->middleware('permission:operative_areas_update')->only(['update','edit']);
        $this->middleware('permission:operative_areas_delete')->only(['delete']);
    }

    /**
     * Display a listing of the resource in json format.
     *
     * @return  \Illuminate\Http\Response
     */
    public function toDatatable(Request $request)
    {
        $user= $request->user();
        $permissions=[
            'operative_areas_read'=> $user->hasPermissionTo('operative_areas_read'),
            'operative_areas_update'=> $user->hasPermissionTo('operative_areas_update'),
            'operative_areas_delete'=> $user->hasPermissionTo('operative_areas_delete')
        ];
        $operative_areas = OperativeArea::all()->map(function($item) use($permissions){
            $items= [                
                [   
                    'permission'=>'operative_areas_read',
                    'name'=>'Show',
                    'action'=>route('operative_areas.show',['id'=>$item->id]),
                    'icon'=>'fa fa-eye',
                    'target'=>'_self',
                ],
                [
                    'permission'=>'operative_areas_update',
                    'name'=>'Edit',
                    'action'=>route('operative_areas.edit',['id'=>$item->id]),
                    'icon'=>'fa fa-edit',
                    'target'=>'_self',
                ],
                [
                    'permission'=>'operative_areas_delete',
                    'name'=>'Delete', 
                    'data_id'=>$item->id,
                    'class_modal'=>'delete-modal',
                    'icon'=>'fa fa-trash-o',
                ],
            ];

            return[
                
                $item->id,
                $item->nombre,
                $item->areaAdministrativa->nombre,
                
                view('settings.permissions', [
                    'items'=>$items,
                    'permissions'=>$permissions
                ])->render()
            ];
        })->all();
        return response()->json(['data'=> $operative_areas ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return  \Illuminate\Http\Response
     */
    public function index()
    {
        
        $columns = "['Id','Nombre', 'Gerencia', 'Actions']";
        $link = 'operative_areas.dt';
        return view('admin.operative_areas.index', compact(['columns','link']));
        
    	//$operative_areas = OperativeArea::all();
        //return view('admin.operative_areas.index', compact(['operative_areas']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return  \Illuminate\Http\Response
     */
    public function create()
    {
        $areas_administrativas= AdministrativeArea::all()->mapWithKeys(function($item){
            return [ $item->id=> $item->nombre ];
        })->toJson();
        $users= User::role('coordinador')->get()->mapWithKeys(function($item){
            return [$item->id => $item->name];
        })->toJson();
        return view('admin.operative_areas.create', compact(['areas_administrativas','users']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param    \Illuminate\Http\Request  $request
     * @return  \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([

	        'nombre'=> 'required|string|max:191',
            'administrative_area_id'=> 'required|exists:administrative_areas,id',            
            'users'=> 'required|array',
            'users.*'=> 'required|exists:users,id'
            
	    ]);

	    $operative_area = OperativeArea::create($request->all());

        $alert=[];
        $alert['status']= 'success';
        $alert['message']= trans('message.successfully_created');
		
		return redirect()->route('operative_areas.index')->with('alert', $alert);
    }

    /**
     * Display the specified resource.
     *
     * @param    \App\OperativeArea  $operative_area
     * @return  \Illuminate\Http\Response
     */
    public function show(Request $request, OperativeArea $operative_area)
    {
        $areas_administrativas= AdministrativeArea::all()->mapWithKeys(function($item){
            return [ $item->id=> $item->nombre ];
        })->toJson();
        $users= User::role('coordinador')->get()->mapWithKeys(function($item){
            return [$item->id => $item->name];
        })->toJson();
        if (! $request->old()) {
            $input_old= $operative_area->toArray();
            $input_old['users']= $operative_area->users()->pluck('id')->toArray();
            $request->replace($input_old);
            $request->flash();
        }

        return view('admin.operative_areas.show', compact(['operative_area','areas_administrativas','users']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param    \App\OperativeArea  $operative_area
     * @return  \Illuminate\Http\Response
     */
    public function edit(Request $request, OperativeArea $operative_area)
    {
        $areas_administrativas= AdministrativeArea::all()->mapWithKeys(function($item){
            return [ $item->id=> $item->nombre ];
        })->toJson();
        $users= User::role('coordinador')->get()->mapWithKeys(function($item){
            return [$item->id => $item->name];
        })->toJson();
    	if (! $request->old()) {
            $input_old= $operative_area->toArray();
            $input_old['users']= $operative_area->users()->pluck('id')->toArray();
            $request->replace($input_old);
            $request->flash();
        }

    	return view('admin.operative_areas.edit', compact(['operative_area','areas_administrativas','users']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param    \Illuminate\Http\Request  $request
     * @param    \App\OperativeArea  $operative_area
     * @return  \Illuminate\Http\Response
     */
    public function update(Request $request, OperativeArea $operative_area)
    {
        $validatedData = $request->validate([

	        'nombre'=> 'required|string|max:191',
            'administrative_area_id'=> 'required|exists:administrative_areas,id',            
            'users'=> 'required|array',
            'users.*'=> 'required|exists:users,id'
            
	    ]);

    	$operative_area->fill($request->all())->save();

    	$alert=[];
        $alert['status']= 'success';
        $alert['message']= trans('message.successfully_updated');;
	            
        return redirect()->route('operative_areas.index')->with('alert', $alert);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param    \App\OperativeArea  $operative_area
     * @return  \Illuminate\Http\Response
     */
    public function destroy(OperativeArea $operative_area)
    {
        $operative_area->delete();

        $alert=[];
        $alert['status']= 'success';
        $alert['message']= trans('message.successfully_deleted');

        return redirect()->route('operative_areas.index')->with('alert', $alert);
    }
}

resources/views/admin/operative_areas/create.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	Areas Operativas
@endsection

@section('contentheader_title')
	Areas Operativas
@endsection

@section('contentheader_description')
	@lang('message.create')
@endsection

@section('main-content')
	<div class="row" id="sectionApp" v-cloak>
		<div class="col-md-12">
			@include('includes.session-alert')
			<form id="form-section" action="{{ route('operative_areas.store') }}" method="POST" enctype="multipart/form-data" @submit.prevent="validateBeforeSubmit">
				<input type="hidden" name="_method" value="POST">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="row">
    				<div class="col-md-8">@include('HTML_VUE.input_text',[ 'label'=>'Nombre', 'placeholder'=>'Nombre', 'model'=>'nombre', 'name'=>"'nombre'", 'validate'=>"'required'"])</div>
                    <div class="col-md-4">@include('HTML_VUE.select_simple',[ 'label'=>'Gerencia', 'placeholder'=>'Gerencia', 'model'=>'administrative_area_id', 'name'=>"'administrative_area_id'", 'validate'=>"'required'",'options'=>'areas_administrativas'])</div>    				                    
                </div>
                <div class="row">
                    <div class="col-md-12">@include('HTML_VUE.checkbox_inline',[ 'label'=>'Usuarios', 'placeholder'=>'Usuarios', 'model'=>'users', 'name'=>"'users'", 'validate'=>"'required'", 'options'=>'usuarios'])</div>
                </div>
                <div class="row">
    				<div class="col-md-12">
    					<button type="submit" class="btn btn-primary">{{trans('message.create')}}</button>
    				</div>
                </div>
			</form>
		</div>
	</div>
@endsection

@section('local-css')
	<style type="text/css">
		[v-cloak] {
			display: none;
		}
		.grid-images-item{
            width: 100%;
            padding-top: 100%;
            border:solid 1px;
            background-size: contain;
            background-position: 50% 50%;
            background-repeat: no-repeat;
        }
        .container-sortable{
            background: transparent;
            border: 1px solid #3c8dbc;
            border-top: 3px solid #3c8dbc;
        }
	</style>
@endsection

@section('local-script')

    <!--<script src="http://liceo_compras.test/js/dist/locale/es.js" type="text/javascript"></script>
    <script src="http://liceo_compras.test/js/moment.min.js"></script>-->

    <script type="text/javascript">
        
        //Vue.use(VeeValidate, {locale:'es'});

        var section = new Vue({
            el: '#sectionApp',
            data: {

            	nombre:`{!!old('nombre')!!}`,
                administrative_area_id:`{!!old('administrative_area_id')!!}`,
                areas_administrativas:{!!$areas_administrativas!!},                
                users:{!!old('users')?json_encode(old('users')):'[]'!!},
                usuarios:{!!$users!!}
            },
            methods: {
            	
	            
                validateBeforeSubmit() {
                    this.$validator.validateAll().then((result) => {
				        if (result) {
				          document.querySelector('#form-section').submit();
				          
				        }else{
				        	alert('Existen errores en el formulario!!!');
				        }
				    });
                },
                addGridImage(e){

                    var model= $(e.currentTarget).data('model');
                    var idx= $(e.currentTarget).data('idx');
                    var info= $(e.currentTarget).data('info');
                    if(idx!=undefined){
                        model= model.replace('index',idx);
                    }
                    console.log('model '+model);
                    console.log('idx '+idx);
                    var files = e.target.files || e.dataTransfer.files;
                    var vm = this;

                    for (var i = 0; i < files.length; i++) {
                        var reader = new FileReader();
                        reader.onload = function(e) {
                            var is_array;
                            eval('is_array= Array.isArray(vm.'+model+');');

                            if(is_array){
                                if(info!=undefined){
                                    console.log('info '+info);
                                    let data={
                                        image: e.target.result,
                                        text1:'',
                                        text2:'',
                                        text3:'',
                                    }
                                    eval('vm.'+model+".push(data);");
                                }else{
                                    eval('vm.'+model+".push(e.target.result);");
                                }
                            }else{
                                eval('vm.'+model+"= e.target.result;");
                            }
                        }
                        reader.readAsDataURL(files[i]);
                    }
                },
                removeGridImage(key,model,index=undefined){
                    console.log('key: '+key+' model: '+model+' index:'+index);
                    if(index != undefined){
                        model= model.replace('index',index);
                    }
                    eval('this.'+model+".splice(key,1);");
                    //this[model].splice(key,1);
                }
            },
            mounted(){
                $(document).on('change', '.input-image', this.addGridImage);
                $(document).on('click', '.box-header .box-tools button.sortable-button', function(){
                    $('i', this).toggleClass('fa-window-minimize');
                    $('i', this).toggleClass('fa-window-maximize');
                });
            }
        });

        //section.$validator.installDateTimeValidators(moment);
        
        @foreach($errors->toArray()?:[] as $key=>$value)
            section.errors.add('{{dot_to_html($key)}}', '{{$errors->first($key)}}');
        @endforeach
        
    </script>
    {{ session()->forget('_old_input') }}
@endsection

resources/views/admin/operative_areas/edit.blade.php
@extends('adminlte::layouts.app')

@section('htmlheader_title')
	Areas Operativas
@endsection

@section('contentheader_title')
	Areas Operativas
@endsection

@section('contentheader_description')
	@lang('message.edit')
@endsection

@section('main-content')
	<div class="row" id="sectionApp" v-cloak>
		<div class="col-md-12">
			@include('includes.session-alert')
			<form id="form-section" action="{{ route('operative_areas.update', $operative_area->id) }}" method="POST" enctype="multipart/form-data" @submit.prevent="validateBeforeSubmit">
				<input type="hidden" name="_method" value="PUT">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="row">
    				<div class="col-md-8">@include('HTML_VUE.input_text',[ 'label'=>'Nombre', 'placeholder'=>'Nombre', 'model'=>'nombre', 'name'=>"'nombre'", 'validate'=>"'required'"])</div>
                    <div class="col-md-4">@include('HTML_VUE.select_simple',[ 'label'=>'Gerencia', 'placeholder'=>'Gerencia', 'model'=>'administrative_area_id', 'name'=>"'administrative_area_id'", 'validate'=>"'required'",'options'=>'areas_administrativas'])</div>    				                    
                </div>
                <div class="row">
                    <div class="col-md-12">@include('HTML_VUE.checkbox_inline',[ 'label'=>'Usuarios', 'placeholder'=>'Usuarios', 'model'=>'users', 'name'=>"'users'", 'validate'=>"'required'", 'options'=>'usuarios'])</div>
                </div>
                <div class="row">
    				<div class="col-md-12">
    					<button type="submit" class="btn btn-primary">{{trans('message.edit')}}</button>
    				</div>
                </div>
			</form>
		</div>
	</div>
@endsection

@section('local-css')
	<style type="text/css">
		[v-cloak] {
			display: none;
		}
		.grid-images-item{
            width: 100%;
            padding-top: 100%;
            border:solid 1px;
            background-size: contain;
            background-position: 50% 50%;
            background-repeat: no-repeat;
        }
        .container-sortable{
            background: transparent;
            border: 1px solid #3c8dbc;
            border-top: 3px solid #3c8dbc;
        }
	</style>
@endsection

@section('local-script')

    <!--<script src="http://liceo_compras.test/js/dist/locale/es.js" type="text/javascript"></script>
    <script src="http://liceo_compras.test/js/moment.min.js"></script>-->

    <script type="text/javascript">
        
        //Vue.use(VeeValidate, {locale:'es'});

        var section = new Vue({
            el: '#sectionApp',
            data: {

            	nombre:`{!!old('nombre')!!}`, 
                administrative_area_id:`{!!old('administrative_area_id')!!}`,
                areas_administrativas:{!!$areas_administrativas!!},                
                users:{!!old('users')?json_encode(old('users')):'[]'!!},
                usuarios:{!!$users!!}
            },
            methods: {
            	
	            
                validateBeforeSubmit() {
                    this.$validator.validateAll().then((result) => {
				        if (result) {
				          document.querySelector('#form-section').submit();
				          
				        }else{
				        	alert('Existen errores en el formulario!!!');
				        }
				    });
                },
                addGridImage(e){

                    var model= $(e.currentTarget).data('model');
                    var idx= $(e.currentTarget).data('idx');
                    var info= $(e.currentTarget).data('info');
                    if(idx!=undefined){
                        model= model.replace('index',idx);
                    }
                    console.log('model '+model);
                    console.log('idx '+idx);
                    var files = e.target.files || e.dataTransfer.files;
                    var vm = this;

                    for (var i = 0; i < files.length; i++) {
                        var reader = new FileReader();
                        reader.onload = function(e) {
                            var is_array;
                            eval('is_array= Array.isArray(vm.'+model+');');

                            if(is_array){
                                if(info!=undefined){
                                    console.log('info '+info);
                                    let data={
                                        image: e.target.result,
                                        text1:'',
                                        text2:'',
                                        text3:'',
                                    }
                                    eval('vm.'+model+".push(data);");
                                }else{
                                    eval('vm.'+model+".push(e.target.result);");
                                }
                            }else{
                                eval('vm.'+model+"= e.target.result;");
                            }
                        }
                        reader.readAsDataURL(files[i]);
                    }
                },
                removeGridImage(key,model,index=undefined){
                    console.log('key: '+key+' model: '+model+' index:'+index);
                    if(index != undefined){
                        model= model.replace('index',index);
                    }
                    eval('this.'+model+".splice(key,1);");
                    //this[model].splice(key,1);
                }
            },
            mounted(){
                $(document).on('change', '.input-image', this.addGridImage);
                $(document).on('click', '.box-header .box-tools button.sortable-button', function(){
                    $('i', this).toggleClass('fa-window-minimize');
                    $('i', this).toggleClass('fa-window-maximize');
                });
            }
        });

        //section.$validator.installDateTimeValidators(moment);
        
        @foreach($errors->toArray()?:[] as $key=>$value)
            section.errors.add('{{dot_to_html($key)}}', '{{$errors->first($key)}}');
        @endforeach
        
    </script>
    {{ session()->forget('_old_input') }}
@endsection